#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
يبني app/src/main/assets/taa_haa_lexicon.txt من قاموس التدقيق الإملائي (Spellchecker Dictionary Builder: ar_SA.dic)
مع قاموس التشكيل الموجود في التطبيق (tashkeel_dict.txt).

الغرض: التفريق بين التاء المربوطة (ة) والهاء (ه) عند القراءة الصوتية.
  #T   كلمات مؤكّدة تنتهي بـ ة (جذوع من قاموس التدقيق + مفاتيح قاموس التشكيل)
  #H   كلمات هاؤها أصلية (الله، هذه، وجه، تنبيه...) فلا تُحوَّل إلى ة أبدًا
  #FIX أخطاء إملائية شائعة (ة بدل ه): هذة -> هذه، اللة -> الله ...

الاستعمال:
  python3 tools/build_taa_lexicon.py --spell ar_SA.dic --tashkeel app/src/main/assets/tashkeel_dict.txt \
          --out app/src/main/assets/taa_haa_lexicon.txt
قاموس التدقيق الخام مليء بالأخطاء (فيه "هذة" و"اللة" كأنها صحيحة) لذلك لا نأخذ منه إلا الجذوع ذات رموز التصريف (/NN)
ونتجاهل الكلمات المصرَّفة المسطّحة.
"""
import argparse


def is_ar(w):
    return all('\u0621' <= c <= '\u064A' for c in w)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--spell', required=True)
    ap.add_argument('--tashkeel', required=True)
    ap.add_argument('--out', required=True)
    a = ap.parse_args()

    stems = set()
    with open(a.spell, encoding='utf-8') as f:
        for line in f:
            line = line.rstrip('\n')
            if not line or line.startswith(':') or line.endswith('.dic') or line.isdigit():
                continue
            w = line.split('\t')[0]
            if '/' in w:
                stems.add(w.split('/')[0])

    tk_t = set()
    with open(a.tashkeel, encoding='utf-8') as f:
        for line in f:
            p = line.rstrip('\n').split('\t')
            if len(p) >= 2 and p[0].endswith('\u0629'):
                tk_t.add(p[0])

    T = {w for w in (stems | tk_t) if w.endswith('\u0629') and len(w) >= 3 and is_ar(w)}
    H = {w for w in stems if w.endswith('\u0647') and len(w) >= 2 and is_ar(w)}
    H |= {'\u0627\u0644\u0644\u0647', '\u0647\u0630\u0647', '\u0625\u0644\u0647', '\u0627\u0644\u0647', '\u0648\u062C\u0647',
          '\u0641\u0642\u0647', '\u0634\u0628\u0647', '\u0646\u0632\u0647', '\u0633\u0641\u0647', '\u062A\u0648\u062C\u064A\u0647',
          '\u062A\u0646\u0628\u064A\u0647', '\u062A\u0646\u0648\u064A\u0647', '\u062A\u0645\u0648\u064A\u0647',
          '\u062A\u0634\u0648\u064A\u0647', '\u062A\u0646\u0632\u064A\u0647', '\u062A\u0631\u0641\u064A\u0647'}

    # أخطاء ة بدل ه (يُستكمل بالسوابق في الكود: و ف ب ل ك ت)
    fix = {
        '\u0647\u0630\u0629': '\u0647\u0630\u0647',        # هذة -> هذه
        '\u0627\u0644\u0644\u0629': '\u0627\u0644\u0644\u0647',  # اللة -> الله
        '\u0644\u0629': '\u0644\u0647',                      # لة -> له
        '\u0628\u0629': '\u0628\u0647',                      # بة -> به
    }

    with open(a.out, 'w', encoding='utf-8', newline='\n') as o:
        o.write('# taa_haa_lexicon: generated by tools/build_taa_lexicon.py (do not edit by hand)\n')
        o.write('#T\n')
        o.write('\n'.join(sorted(T)) + '\n')
        o.write('#H\n')
        o.write('\n'.join(sorted(H)) + '\n')
        o.write('#FIX\n')
        for k in sorted(fix):
            o.write(k + '=' + fix[k] + '\n')
    print('T', len(T), 'H', len(H), 'FIX', len(fix))


if __name__ == '__main__':
    main()
